### ISSUE TITLE
Feature #1 : User can enter their baby’s name in the shopping list title.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/BabyBuy#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter their baby’s name in the shopping list title.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can include their baby's name in the shopping list tile to show it is created specifically for him/her.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/76827487/142974781-628d748e-60d9-4c33-b55f-846933e1f337.png)

![image](https://user-images.githubusercontent.com/76827487/142974938-82e17558-1426-4ce4-b975-cd380e891369.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add users table to database.

### ☁️ Server

- [x] Create endpoint POST to save a baby's name.
- [x] Create endpoint POST to save user's due date.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for app's first page.
- [x] Add a form entry for due date.
- [x] Add a form entry for baby's name.
- [x] Add enter button to save data to database and to continue to home page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
