### ISSUE TITLE
Feature #2: User can set the due date to complete their shopping list

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/BabyBuy#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set the due date to complete their shopping list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can set their due date or target date to see how many days left to complete their shopping.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/76827487/143177826-a272f44f-dce2-4bff-8ad7-1fb2e8363081.png)

![image](https://user-images.githubusercontent.com/76827487/143177869-381e2401-ac26-49b2-8af0-ef573a3f54c8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component for home page.
- [ ] Add a function to show baby's name in the shopping list title.
- [ ] Add a function to calculate the remaining days based on due date.
- [ ] Add some temporarily default categories in daily update and categories sections.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
